import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"

import Header from "@/components/shared/header"
import { cn } from "@/utils/clsx"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "px-4")}>
        <Header />
        {children}
      </body>
    </html>
  )
}
