import type { Meta, StoryObj } from "@storybook/react"

import { Payment } from "@/types/paymentType"
import { columns } from "./columns"
import { PaymentTable } from "./payment-table"

const data = [
  {
    id: "728ed52f",
    amount: 100,
    emoji: "🍕",
    category: "Food",
    name: "Pizza",
    description: "Best Pizza in Town",
    date: new Date(2023, 6, 1),
  },
  {
    id: "728ed52g",
    amount: 200,
    emoji: "🍔",
    category: "Food",
    name: "Burger",
    description: "Best Burger in Town",
    date: new Date(2023, 6, 5),
  },
  {
    id: "728ed52h",
    amount: 300,
    emoji: "🍟",
    category: "Food",
    name: "Fries",
    description: "Best Fries in Town",
    date: new Date(2023, 6, 10),
  },
  {
    id: "728ed52i",
    amount: 400,
    emoji: "🚿",
    category: "Utilities",
    name: "Water",
    description: "OSE",
    date: new Date(2023, 6, 15),
  },
  {
    id: "728ed52j",
    amount: 150,
    emoji: "🍦",
    category: "Food",
    name: "Ice Cream",
    description: "Best Ice Cream in Town",
    date: new Date(2023, 6, 20),
  },
  {
    id: "728ed52k",
    amount: 50,
    emoji: "🥤",
    category: "Food",
    name: "Soda",
    description: "Best Soda in Town",
    date: new Date(2023, 6, 25),
  },
  {
    id: "728ed52l",
    amount: 250,
    emoji: "🍗",
    category: "Food",
    name: "Chicken",
    description: "Best Chicken in Town",
    date: new Date(2023, 7, 1),
  },
  {
    id: "728ed52m",
    amount: 120,
    emoji: "🍹",
    category: "Food",
    name: "Cocktail",
    description: "Best Cocktail in Town",
    date: new Date(2023, 7, 5),
  },
  {
    id: "728ed52n",
    amount: 180,
    emoji: "🍝",
    category: "Food",
    name: "Pasta",
    description: "Best Pasta in Town",
    date: new Date(2023, 7, 10),
  },
  {
    id: "728ed52o",
    amount: 50,
    emoji: "💡",
    category: "Utilities",
    name: "Electricity",
    description: "UTE",
    date: new Date(2023, 7, 15),
  },
  {
    id: "728ed52p",
    amount: 30,
    emoji: "📱",
    category: "Utilities",
    name: "Phone Bill",
    description: "ANTEL",
    date: new Date(2023, 7, 20),
  },
  {
    id: "728ed52q",
    amount: 100,
    emoji: "📺",
    category: "Entertainment",
    name: "TV Subscription",
    description: "DirectTV",
    date: new Date(2023, 7, 25),
  },
  {
    id: "728ed52r",
    amount: 70,
    emoji: "📚",
    category: "Education",
    name: "Books",
    description: "Best Books in Town",
    date: new Date(2023, 8, 1),
  },
  {
    id: "728ed52s",
    amount: 90,
    emoji: "✈️",
    category: "Travel",
    name: "Flight Ticket",
    description: "Trip to Miami",
    date: new Date(2023, 8, 5),
  },
  {
    id: "728ed52t",
    amount: 80,
    emoji: "🍰",
    category: "Food",
    name: "Cake",
    description: "Best Cake in Town",
    date: new Date(2023, 8, 10),
  },
  {
    id: "728ed52u",
    amount: 150,
    emoji: "🥩",
    category: "Food",
    name: "Steak",
    description: "Best Steak in Town",
    date: new Date(2023, 8, 15),
  },
  {
    id: "728ed52v",
    amount: 25,
    emoji: "🍵",
    category: "Food",
    name: "Tea",
    description: "Best Tea in Town",
    date: new Date(2023, 8, 20),
  },
  {
    id: "728ed52w",
    amount: 60,
    emoji: "🍣",
    category: "Food",
    name: "Sushi",
    description: "Best Sushi in Town",
    date: new Date(2023, 8, 25),
  },
  {
    id: "728ed52x",
    amount: 200,
    emoji: "🍷",
    category: "Food",
    name: "Wine",
    description: "Best Wine in Town",
    date: new Date(2023, 9, 1),
  },
  {
    id: "728ed52y",
    amount: 50,
    emoji: "💻",
    category: "Utilities",
    name: "Internet Bill",
    description: "ANTEL",
    date: new Date(2023, 9, 5),
  },
  {
    id: "728ed52z",
    amount: 120,
    emoji: "🔌",
    category: "Utilities",
    name: "Power Adapter",
    description: "Best Power Adapter in Town",
    date: new Date(2023, 9, 10),
  },
  {
    id: "728ed530",
    amount: 80,
    emoji: "🎮",
    category: "Entertainment",
    name: "Video Game",
    description: "Best Video Game in Town",
    date: new Date(2023, 9, 15),
  },
  {
    id: "728ed531",
    amount: 40,
    emoji: "🎬",
    category: "Entertainment",
    name: "Movie Ticket",
    description: "Best Movie Ticket in Town",
    date: new Date(2023, 9, 20),
  },
  {
    id: "728ed532",
    amount: 120,
    emoji: "📓",
    category: "Education",
    name: "Notebooks",
    description: "Best Notebooks in Town",
    date: new Date(2023, 9, 25),
  },
  {
    id: "728ed533",
    amount: 180,
    emoji: "🥗",
    category: "Food",
    name: "Salad",
    description: "Best Salad in Town",
    date: new Date(2024, 0, 5),
  },
  {
    id: "728ed534",
    amount: 300,
    emoji: "🍕",
    category: "Food",
    name: "Pizza",
    description: "Best Pizza in Town",
    date: new Date(2024, 0, 10),
  },
  {
    id: "728ed535",
    amount: 150,
    emoji: "🍔",
    category: "Food",
    name: "Burger",
    description: "Best Burger in Town",
    date: new Date(2024, 1, 2),
  },
  {
    id: "728ed536",
    amount: 250,
    emoji: "🍟",
    category: "Food",
    name: "Fries",
    description: "Best Fries in Town",
    date: new Date(2024, 1, 15),
  },
  {
    id: "728ed537",
    amount: 120,
    emoji: "🚿",
    category: "Utilities",
    name: "Water",
    description: "OSE",
    date: new Date(2024, 2, 1),
  },
  {
    id: "728ed538",
    amount: 200,
    emoji: "🍦",
    category: "Food",
    name: "Ice Cream",
    description: "Best Ice Cream in Town",
    date: new Date(2024, 2, 10),
  },
  {
    id: "728ed539",
    amount: 50,
    emoji: "🥤",
    category: "Food",
    name: "Soda",
    description: "Best Soda in Town",
    date: new Date(2024, 3, 5),
  },
  {
    id: "728ed53a",
    amount: 180,
    emoji: "🍗",
    category: "Food",
    name: "Chicken",
    description: "Best Chicken in Town",
    date: new Date(2024, 3, 20),
  },
  {
    id: "728ed53b",
    amount: 120,
    emoji: "🍹",
    category: "Food",
    name: "Cocktail",
    description: "Best Cocktail in Town",
    date: new Date(2024, 4, 5),
  },
  {
    id: "728ed53c",
    amount: 200,
    emoji: "🍝",
    category: "Food",
    name: "Pasta",
    description: "Best Pasta in Town",
    date: new Date(2024, 5, 20),
  },
  {
    id: "728ed53d",
    amount: 50,
    emoji: "💡",
    category: "Utilities",
    name: "Electricity",
    description: "UTE",
    date: new Date(2024, 5, 1),
  },
  {
    id: "728ed53e",
    amount: 30,
    emoji: "📱",
    category: "Utilities",
    name: "Phone Bill",
    description: "ANTEL",
    date: new Date(2024, 5, 15),
  },
  {
    id: "728ed53f",
    amount: 100,
    emoji: "📺",
    category: "Entertainment",
    name: "TV Subscription",
    description: "DirectTV",
    date: new Date(2024, 5, 1),
  },
  {
    id: "728ed53g",
    amount: 70,
    emoji: "📚",
    category: "Education",
    name: "Books",
    description: "Best Books in Town",
    date: new Date(2024, 5, 15),
  },
  {
    id: "728ed53h",
    amount: 90,
    emoji: "✈️",
    category: "Travel",
    name: "Flight Ticket",
    description: "Trip to Miami",
    date: new Date(2024, 5, 1),
  },
  {
    id: "728ed53i",
    amount: 80,
    emoji: "🍰",
    category: "Food",
    name: "Cake",
    description: "Best Cake in Town",
    date: new Date(2024, 6, 10),
  },
  {
    id: "628ed53j",
    amount: 150,
    emoji: "🥩",
    category: "Food",
    name: "Steak",
    description: "Best Steak in Town",
    date: new Date(2024, 6, 5),
  },
  {
    id: "628ed53k",
    amount: 25,
    emoji: "🍵",
    category: "Food",
    name: "Tea",
    description: "Best Tea in Town",
    date: new Date(2024, 6, 20),
  },
  {
    id: "628ed53l",
    amount: 560,
    emoji: "🍣",
    category: "Food",
    name: "Sushi",
    description: "Best Sushi in Town",
    date: new Date(2024, 6, 5),
  },
  {
    id: "628ed53m",
    amount: 290,
    emoji: "🍷",
    category: "Food",
    name: "Wine",
    description: "Best Wine in Town",
    date: new Date(2024, 6, 20),
  },
  {
    id: "628ed53n",
    amount: 350,
    emoji: "💻",
    category: "Utilities",
    name: "Internet Bill",
    description: "ANTEL",
    date: new Date(2024, 6, 1),
  },
  {
    id: "628ed53o",
    amount: 120,
    emoji: "🔌",
    category: "Utilities",
    name: "Power Adapter",
    description: "Best Power Adapter in Town",
    date: new Date(2024, 6, 15),
  },
  {
    id: "628ed53p",
    amount: 180,
    emoji: "🎮",
    category: "Entertainment",
    name: "Video Game",
    description: "Best Video Game in Town",
    date: new Date(2024, 6, 1),
  },
  {
    id: "628ed53q",
    amount: 420,
    emoji: "🎬",
    category: "Entertainment",
    name: "Movie Ticket",
    description: "Best Movie Ticket in Town",
    date: new Date(2024, 6, 15),
  },
  {
    id: "628ed53r",
    amount: 1020,
    emoji: "📓",
    category: "Education",
    name: "Notebooks",
    description: "Best Notebooks in Town",
    date: new Date(2024, 6, 30),
  },
  {
    id: "628ed53s",
    amount: 40,
    emoji: "🎬",
    category: "Entertainment",
    name: "Movie Ticket",
    description: "Best Movie Ticket in Town",
    date: new Date(2024, 6, 30),
  },
] as Payment[]

const meta = {
  title: "PaymentTable",
  component: PaymentTable,
  parameters: {
    backgrounds: {
      default: "light",
    },
    argTypes: {
      columns: { control: "object" },
      data: { control: "object" },
    },
  },

  tags: ["autodocs"],
} satisfies Meta<typeof PaymentTable>

export default meta

type Story = StoryObj<typeof meta>

export const Primary: Story = {
  args: {
    columns: columns as any,
    data,
  },
}
